---
title: "jasa-mandarin_retroflex"
author: "Kate Shan Luo"
date: "7/29/2020"
output:
  html_document: default
  pdf_document: default
---

```{r}
library(lme4)
library(lmerTest)
library(lsmeans)
library(ggplot2)
library(pastecs)
library(Hmisc)
library(MASS)
library(dplyr)
library(knitr)
library(broom)
library(groupdata2)
library(caret)
library(tidyverse)
library(sjPlot)
library(sjstats)
library(scales)
library(rattle)
library(heplots)
library(klaR)
library(gridExtra)
library(cowplot)
library(multcompView)
library(ggpubr)
library(gss)
library(lme4)
library(lmerTest)
library(lsmeans)
library(ggplot2)
library(pastecs)
library(Hmisc)
library(MASS)
library(dplyr)
library(knitr)
library(broom)
library(groupdata2)
library(caret)
library(tidyverse)
library(sjPlot)
library(sjstats)
library(scales)
library(rattle)
library(heplots)
library(klaR)
library(gridExtra)
library(cowplot)
library(multcompView)
library(ggpubr)
library(gss)
library(extrafont)
```

#Table 3
```{r}
data = read.csv("datar1.csv",header=TRUE)
save(data, file = "data.RData")
load(file="data.RData")

table(data$Rating)

data$Rating = factor(data$Rating,
                             levels = c("bunched","retroflex","humped"),
                             labels = c("Bunched","Retroflex","Humped"))

data$Grouping = factor(data$Grouping,
                       levels =c("Alveolar","Retroflex"),
                       labels = c("Alveolar","Retroflex"))

data$Consonant=factor(data$Consonant,
                           levels = c("c", "s", "z","ch","sh","zh"),
                           labels = c("ʦʰ", "s", "ʦ","tʂʰ","ʂ","tʂ"))

data$Following_Vowel=factor(data$Following_Vowel,
                      levels = c("i", "a", "u"),
                      labels = c("i", "a", "u"))

data$Gender =factor(data$Gender,
                            levels = c("F", "M"),
                            labels = c("F", "M"))

data$F3F2Distance = data$F3_mean - data$F2_mean


#Table 3
aggregate(Curvature_Location ~ Rating, data,stat.desc) 
aggregate(Curvature_Degree ~ Rating, data,stat.desc)
aggregate(COG ~ Rating, data,stat.desc)
aggregate(F3_mean~ Rating, data,stat.desc)
aggregate(F3F2Distance~ Rating, data,stat.desc)
```


#Figure 3 articulatory values boxplots
```{r}
cleanup = theme(panel.grid.major = element_blank(),
                panel.grid.minor = element_blank(),
                panel.background = element_blank(),
                axis.line = element_line(color = "black"))


cdegreenotched = ggplot(data,aes(x=Consonant,y=Curvature_Degree,fill=Grouping))+
  geom_boxplot(notch =TRUE)+
  xlab("")+ylab("Curvature Degree")+
  stat_compare_means(ref.group = "ʦʰ",method = "t.test",label = "p.signif",label.y = 0.55,hide.ns = TRUE)+
  cleanup


CuvatureLocationnotched = ggplot(data,aes(x=Consonant,y=Curvature_Location,fill=Grouping))+
  geom_boxplot(notch =TRUE)+
  xlab("")+ylab("Curvature Location")+
  stat_compare_means(ref.group = "ʦʰ",method = "t.test",label = "p.signif",label.y = 0.75,hide.ns = TRUE)+
  cleanup

MCInotched= ggplot(data,aes(x=Consonant,y=MCI,fill=Grouping))+
  geom_boxplot(notch =TRUE)+
  xlab("")+ylab("MCI")+
  stat_compare_means(ref.group = "ʦʰ",method = "t.test",label = "p.signif",label.y = 4,hide.ns = TRUE)+
  cleanup

c1realnotched= ggplot(data,aes(x=Consonant,y=real_1,fill=Grouping))+
  geom_boxplot(notch =TRUE)+
  xlab("")+ylab("C1_real")+
  stat_compare_means(ref.group = "ʦʰ",method = "t.test",label = "p.signif",label.y = 38,hide.ns = TRUE)+
  cleanup


C1imagnotched = ggplot(data,aes(x=Consonant,y=imag_1,fill=Grouping))+
  geom_boxplot(notch =TRUE)+
  xlab("")+ylab("C1_imag")+
  stat_compare_means(ref.group = "ʦʰ",method = "t.test",label = "p.signif",label.y = -3,hide.ns = TRUE)+
  cleanup

g=ggarrange(c1realnotched,C1imagnotched, 
               CuvatureLocationnotched,cdegreenotched,
               MCInotched,
              ncol = 2, nrow = 3,
               common.legend=TRUE,legend="bottom")

ggsave(g,filename= "Fig3_plot.png",dpi = 400, width = 10, height = 8, units = "in")

```


#figure 6 acoustic notched boxed plots

```{r}
F1notched = ggplot(data,aes(x=Consonant,y=F1_mean,fill=Grouping))+
  geom_boxplot(notch =TRUE)+
  xlab("")+ylab("F1")+
  stat_compare_means(ref.group = "ʦʰ",method = "t.test",label = "p.signif",label.y = 1800,hide.ns = TRUE)+
  theme(legend.position = "none") +
  cleanup


F2notched = ggplot(data,aes(x=Consonant,y=F2_mean,fill=Grouping))+
  geom_boxplot(notch =TRUE)+
  xlab("")+ylab("F2")+
  stat_compare_means(ref.group = "ʦʰ",method = "t.test",label = "p.signif",label.y = 2800,hide.ns = TRUE)+
  theme(legend.position = "none") +
  cleanup


F3notched = ggplot(data,aes(x=Consonant,y=F3_mean,fill=Grouping))+
  geom_boxplot(notch =TRUE)+
  xlab("")+ylab("F3")+
  stat_compare_means(ref.group = "ʦʰ",method = "t.test",label = "p.signif",label.y = 3800,hide.ns = TRUE)+
  theme(legend.position = "none") +
  cleanup


COGnotched = ggplot(data,aes(x=Consonant,y=COG,fill=Grouping))+
  geom_boxplot(notch =TRUE)+
  xlab("")+ylab("COG")+
  stat_compare_means(ref.group = "ʦʰ",method = "t.test",label = "p.signif",label.y = 7500,hide.ns = TRUE)+
  cleanup


skewnotched = ggplot(data,aes(x=Consonant,y=SKEW,fill=Grouping))+
  geom_boxplot(notch =TRUE)+
  xlab("")+ylab("Skewness")+
  stat_compare_means(ref.group = "ʦʰ",method = "t.test",label = "p.signif",label.y = 1.3,hide.ns = TRUE)+
  theme(legend.position = "none") +
  cleanup


dispersionnotched = ggplot(data,aes(x=Consonant,y=SD,fill=Grouping))+
  geom_boxplot(notch =TRUE)+
  xlab("")+ylab("Dispersion")+
  stat_compare_means(ref.group = "ʦʰ",method = "t.test",label = "p.signif",label.y = 3500,hide.ns = TRUE)+
  theme(legend.position = "none") +
  cleanup

F3F2notched = ggplot(data,aes(x=Consonant,y=F3F2Distance,fill=Grouping))+
  geom_boxplot(notch =TRUE)+
  xlab("")+ylab("F3F2Distance")+
  stat_compare_means(ref.group = "ʦʰ",method = "t.test",label = "p.signif",label.y = 1500,hide.ns = TRUE)+
  theme(legend.position = "none") +
  cleanup


acousg = ggarrange(F1notched, F2notched, 
                    F3notched, F3F2notched,
                    COGnotched, dispersionnotched,
                   skewnotched,
                      ncol=2,nrow = 4,
                      common.legend = TRUE,legend ="bottom")

ggsave(acousg,filename= "Fig6_plot.png",dpi = 400, width = 10, height = 10, units = "in")

```

##polar lme Table 4 & 5
```{r}
datapolar = read.csv("datapolar.csv",header=TRUE)

save(datapolar, file = "datapolar.RData")

load(file="datapolar.RData")

datapolar$Consonant=factor(datapolar$Consonant,
                     levels = c("c", "s", "z","ch","sh","zh"),
                     labels = c("ʦʰ", "s", "ʦ","tʂʰ","ʂ","tʂ"))

datapolar$Grouping = datapolar$Consonant

levels(datapolar$Grouping) <- list(Alveolar=c("ʦʰ","s","ʦ"),Retroflex=c("tʂʰ","ʂ","tʂ"))

datapolar$Vowel=factor(datapolar$Vowel,
                            levels = c("i", "a", "u"),
                            labels = c("i", "a", "u"))

datapolar$Participant = factor(datapolar$Participant,
                              levels = c("P1","P2","P3","P4","P5","P6","P7","P8","P9","P10",                                      "P11","P12","P13","P14","P15","P16","P17","P18","P19"),
                              labels = c("P1","P2","P3","P4","P5","P6","P7","P8","P9","P10",
                                         "P11","P12","P13","P14","P15","P16","P17","P18","P19"))

datapolar$Section = factor(datapolar$Section,
                           levels = c("Front","Back"),
                           labels = c("Front","Back"))

datapolar = na.omit(datapolar)

summary(datapolar)

radiusfront1model = lmer(Radius ~ Grouping * Vowel + (1+Grouping | Participant) + (1+Vowel|Participant), data = subset(datapolar,Section =="Front"),REML= F)

radiusfrontmodel = lmer(Radius ~ Grouping + Vowel + (1+Grouping | Participant) + (1+Vowel|Participant),data = subset(datapolar,Section =="Front"),REML= F)

anova(radiusfront1model,radiusfrontmodel)
      
#table 4
summary(radiusfrontmodel)

radiusback1model = lmer(Radius ~ Grouping * Vowel + (1+Grouping | Participant) + (1+Vowel|Participant), data = subset(datapolar, Section =="Back"),REML= F)

radiusbackmodel = lmer(Radius ~ Grouping + Vowel + (1+Grouping | Participant) + (1+Vowel|Participant),data = subset(datapolar, Section =="Back"),REML= F)

anova(radiusback1model, radiusbackmodel)

#table 5
summary(radiusbackmodel)

```

##Figure 4
```{r}

couleurs=c("darkorange","grey")

Figure4plot = partimat(Grouping ~ Curvature_Degree +Curvature_Location , data=subset(data, Participant == "P2"), method="lda",na.action=na.omit, prec=100,display.points=FALSE,
image.colors = couleurs,main = "LDA results using Curvature Location and Curvature Degree for P2", size=12)

dev.copy(png, filename="Fig4_plot.png",res = 400, width = 10, height = 6, units = "in")
dev.off()

```


##Figure 5
```{r}

Figure5plot = partimat(Grouping ~ imag_1 + real_1  , data=subset(data, Participant == "P2"),
                       method="lda",na.action=na.omit, prec=100,display.points=FALSE,
                       image.colors = couleurs,main = "LDA results using C1_real and C1_imag for P2", size=12)

dev.copy(png, filename="Fig5_plot.png",res = 400, width = 10, height = 6, units = "in")
dev.off()

```

###Figure 7
```{r echo=FALSE}
data$Dispersion = data$SD
data$Skewness = data$SKEW

Fig7plot = partimat(Grouping ~  COG + Dispersion + Skewness + F1_mean + F2_mean, data=data,method="lda",na.action=na.omit, prec=100,display.points=FALSE, main =  "LDA results using five acoustic values across participants", image.colors = couleurs)

dev.copy(png,filename="Fig7_plot.png",res = 400, width = 10, height = 8, units = "in")

dev.off()

```


##Figure 2
```{r}

datassanova = read.csv("datassanova.csv",header=TRUE)

save(datassanova, file = "datassanova.RData")

load(file="datassanova.RData")

datassanova$Section <- NULL 

datassanova$Consonant=factor(datassanova$Consonant,
                      levels = c("c","ch", "s", "sh", "z","zh"),
                      labels = c("ʦʰ","tʂʰ","s", "ʂ", "ʦ","tʂ"))

datassanova$Vowel =factor(datassanova$Vowel,
                          levels = c("i","a","u"),
                          labels = c("i","a","u"))

datassanova$Grouping = datassanova$Consonant

levels(datassanova$Grouping) <- list(Alveolar=c("ʦʰ","s","ʦ"),Retroflex=c("tʂʰ","ʂ","tʂ"))


datassanova$Participant = factor(datassanova$Participant,
                               levels = c("P1","P2","P3","P4","P5","P6","P7","P8","P9","P10",   "P11","P12","P13","P14","P15","P16","P17","P18","P19"),
                               labels = c("P1","P2","P3","P4","P5","P6","P7","P8","P9","P10",                                         "P11","P12","P13","P14","P15","P16","P17","P18","P19"))


source('~/Dropbox/Ultrasound/Literature Mandarin rhotic/Mandarin retroflex R/Mandarin retroflex fricative/tongue_ssanova.r')

###p1 tongue ssanove 


p1data = subset(datassanova,Participant == "P1")

p1.tongue = ssanova(Y~Consonant + X + Consonant:X, data=p1data)
p1.tongue.grid <- expand.grid(X = seq(min(p1data$X),max(p1data$X), length = 42), Consonant=levels(p1data$Consonant)) 
p1.tongue.grid$Fit <- predict(p1.tongue, newdata = p1.tongue.grid, se = T)$fit 
p1.tongue.grid$SE <- predict(p1.tongue, newdata = p1.tongue.grid, se = T)$se.fit 

par(pty="s")
comparison.p1 <- ggplot(p1.tongue.grid,aes(x=X, color=Consonant), res=300)
p1ssanova = comparison.p1 + geom_line(aes(y=Fit), size=2, alpha = .8) +
  scale_color_brewer(type="seq", palette = "Paired")+
  ylab("") +xlab("P1(F)")+
  geom_line(aes(y=Fit+(1.96*SE)),lty=2,alpha=0.8)+
  geom_line(aes(y=Fit-(1.96*SE)),lty=2,alpha=0.8)+
  theme(legend.position = "none")


##p2 tongue ssanova


p2.tongue = ssanova(Y~Consonant + X + Consonant:X, data=subset(datassanova,Participant =="P2"))
p2.tongue.grid <- expand.grid(X = seq(min(subset(datassanova,Participant =="P2")$X),max(subset(datassanova,Participant =="P2")$X), length = 42), Consonant=levels(data$Consonant)) 
p2.tongue.grid$Fit <- predict(p2.tongue, newdata = p2.tongue.grid, se = T)$fit 
p2.tongue.grid$SE <- predict(p2.tongue, newdata = p2.tongue.grid, se = T)$se.fit 

par(pty="s")
comparison.p2 <- ggplot(p2.tongue.grid,aes(x=X, color=Consonant), res=300)
p2ssanova = comparison.p2 + geom_line(aes(y=Fit), size=2, alpha = .8) +
  scale_color_brewer(type="seq", palette = "Paired")+
  ylab("") +xlab("P2(M)")+
  geom_line(aes(y=Fit+(1.96*SE)),lty=2,alpha=0.8)+
  geom_line(aes(y=Fit-(1.96*SE)),lty=2,alpha=0.8)+
  theme(legend.position="none")

###p7 ssanova

p7data = subset(datassanova,Participant == "P7")

p7data <- na.omit(p7data)

p7.tongue = ssanova(Y~Consonant + X + Consonant:X, data=p7data)
p7.tongue.grid <- expand.grid(X = seq(min(p7data$X),max(p7data$X),
                                      length = 42), Consonant=levels(data$Consonant)) 
p7.tongue.grid$Fit <- predict(p7.tongue, newdata = p7.tongue.grid, se = T)$fit 
p7.tongue.grid$SE <- predict(p7.tongue, newdata = p7.tongue.grid, se = T)$se.fit 

par(pty="s")
comparison.p7 <- ggplot(p7.tongue.grid,aes(x=X, color=Consonant), res=300)
p7ssanova = comparison.p7 + geom_line(aes(y=Fit), size=2, alpha = .8) +
  scale_color_brewer(type="seq", palette = "Paired")+
  ylab("") +xlab("P7(M)")+
  geom_line(aes(y=Fit+(1.96*SE)),lty=2,alpha=0.8)+
  geom_line(aes(y=Fit-(1.96*SE)),lty=2,alpha=0.8)+
  theme(legend.position="none")

###p8 ssanova
p8.tongue = ssanova(Y~Consonant + X + Consonant:X, data=subset(datassanova,Participant =="P8"))
p8.tongue.grid <- expand.grid(X = seq(min(subset(datassanova,Participant =="P8")$X),max(subset(datassanova,Participant =="P8")$X), length  = 42), Consonant=levels(data$Consonant)) 
p8.tongue.grid$Fit <- predict(p8.tongue, newdata = p8.tongue.grid, se = T)$fit 
p8.tongue.grid$SE <- predict(p8.tongue, newdata = p8.tongue.grid, se = T)$se.fit 

par(pty="s")
comparison.p8 <- ggplot(p8.tongue.grid,aes(x=X, color=Consonant), res=300)
p8ssanova = comparison.p8 + geom_line(aes(y=Fit), size=2, alpha = .8) +
  scale_color_brewer(type="seq", palette = "Paired")+
  ylab("") +xlab("P8(F)")+
  geom_line(aes(y=Fit+(1.96*SE)),lty=2,alpha=0.8)+
  geom_line(aes(y=Fit-(1.96*SE)),lty=2,alpha=0.8)+
  theme(legend.position="none")

fig2 = ggarrange(p1ssanova,p2ssanova,p7ssanova,p8ssanova,
                    common.legend = TRUE,legend = "bottom")

ggsave(fig2,filename= "Fig2_plot.png",dpi = 400, width = 6, height = 6, units = "in")

```


#LDA Results using articulatory Table 6
```{r}
articulatory5 = lda(Grouping ~ real_1 + imag_1 + MCI + Curvature_Degree + Curvature_Location, data=data)
p.articulatory5  = predict(articulatory5,data)
p.articulatory5.class = p.articulatory5$class
p.articulatory5.table = table(p.articulatory5.class, data$Grouping)
articulatory5_accur = sum(diag(p.articulatory5.table))/sum(p.articulatory5.table)
print(articulatory5_accur)

ClocationC1.lda = lda(Grouping ~ real_1 + Curvature_Location, data=data)
p.ClocationC1.lda  = predict(ClocationC1.lda,data)
p.ClocationC1.lda.class = p.ClocationC1.lda$class
p.ClocationC1.lda.table = table(p.ClocationC1.lda.class, data$Grouping)
ClocationC1.lda_accur = sum(diag(p.ClocationC1.lda.table))/sum(p.ClocationC1.lda.table)
print(ClocationC1.lda_accur)

CL.lda = lda(Grouping ~ Curvature_Location, data=data)
p.CL.lda = predict(CL.lda,data)
p.CL.lda.class = p.CL.lda$class
p.CL.lda.table = table(p.CL.lda.class, data$Grouping)
CL.lda_accur = sum(diag(p.CL.lda.table))/sum(p.CL.lda.table)
print(CL.lda_accur)

CD.lda = lda(Grouping ~ Curvature_Degree, data=data)
p.CD.lda = predict(CD.lda,data)
p.CD.lda.class = p.CD.lda$class
p.CD.lda.table = table(p.CD.lda.class, data$Grouping)
CD.lda_accur = sum(diag(p.CD.lda.table))/sum(p.CD.lda.table)
print(CD.lda_accur)

mci.lda = lda(Grouping ~ MCI, data=data)
p.mci.lda = predict(mci.lda,data)
p.mci.lda.class = p.mci.lda$class
p.mci.lda.table = table(p.mci.lda.class, data$Grouping)
mci.lda_accur = sum(diag(p.mci.lda.table))/sum(p.mci.lda.table)
print(mci.lda_accur)

cdcl.lda = lda(Grouping ~  Curvature_Degree + Curvature_Location, data=data)
p.cdcl.lda = predict(cdcl.lda,data)
p.cdcl.lda.class = p.cdcl.lda$class
p.cdcl.lda.table = table(p.cdcl.lda.class, data$Grouping)
cdcl.lda_accur = sum(diag(p.cdcl.lda.table))/sum(p.cdcl.lda.table)
print(cdcl.lda_accur)

c1mci.lda = lda(Grouping ~ real_1 + MCI, data=data)
p.c1mci.lda = predict(c1mci.lda,data)
p.c1mci.lda.class = p.c1mci.lda$class
p.c1mci.lda.table = table(p.c1mci.lda.class, data$Grouping)
c1mci.lda_accur = sum(diag(p.c1mci.lda.table))/sum(p.c1mci.lda.table)
print(c1mci.lda_accur)


cdclc1.lda = lda(Grouping ~ real_1 + Curvature_Degree + Curvature_Location, data=data)
p.cdclc1.lda = predict(cdclc1.lda,data)
p.cdclc1.lda.class = p.cdclc1.lda$class
p.cdclc1.lda.table = table(p.cdclc1.lda.class, data$Grouping)
cdclc1.lda_accur = sum(diag(p.cdclc1.lda.table))/sum(p.cdclc1.lda.table)
print(cdclc1.lda_accur)

clmcic1.lda = lda(Grouping ~ real_1 + MCI + Curvature_Location, data=data)
p.clmcic1.lda = predict(clmcic1.lda,data)
p.clmcic1.lda.class = p.clmcic1.lda$class
p.clmcic1.lda.table = table(p.clmcic1.lda.class, data$Grouping)
clmcic1.lda_accur = sum(diag(p.clmcic1.lda.table))/sum(p.clmcic1.lda.table)
print(clmcic1.lda_accur)

cdmcic1.lda = lda(Grouping ~ real_1 + MCI + Curvature_Degree, data=data)
p.cdmcic1.lda = predict(cdmcic1.lda,data)
p.cdmcic1.lda.class = p.cdmcic1.lda$class
p.cdmcic1.lda.table = table(p.cdmcic1.lda.class, data$Grouping)
cdmcic1.lda_accur = sum(diag(p.cdmcic1.lda.table))/sum(p.cdmcic1.lda.table)
print(cdmcic1.lda_accur)
```

```{r}
cdmcic1.lda = lda(Grouping ~ real_1 + MCI + Curvature_Degree, data=data)
p.cdmcic1.lda = predict(cdmcic1.lda,data)
p.cdmcic1.lda.class = p.cdmcic1.lda$class
p.cdmcic1.lda.table = table(p.cdmcic1.lda.class, data$Grouping)
cdmcic1.lda_accur = sum(diag(p.cdmcic1.lda.table))/sum(p.cdmcic1.lda.table)
print(cdmcic1.lda_accur)
```

```{r}
##Table 7a
articulatory4 = lda(Grouping ~ real_1 + MCI + Curvature_Degree + Curvature_Location, data=data)
p.articulatory4  = predict(articulatory4,data)
p.articulatory4.class = p.articulatory4$class
p.articulatory4.table = table(p.articulatory4.class, data$Grouping)
print(p.articulatory4.table)
articulatory4_accur = sum(diag(p.articulatory4.table))/sum(p.articulatory4.table)
print(articulatory4_accur)


##Table 7b
articulatory4_sound = lda(Consonant ~ real_1 + MCI + Curvature_Degree + Curvature_Location, data=data)
p.articulatory4_sound  = predict(articulatory4_sound,data)
p.articulatory4_sound.class = p.articulatory4_sound$class
p.articulatory4_sound.table = table(p.articulatory4_sound.class, data$Consonant)
print(p.articulatory4_sound.table)
```


##LDA in different vowel contexts sample 
```{r}
voweli = subset(data,Following_Vowel == "i")
vowela = subset(data,Following_Vowel == "a")
vowelu = subset(data,Following_Vowel == "u")

CLvoweli.lda = lda(Grouping ~ Curvature_Location, data=voweli)
p.CLvoweli.lda = predict(CLvoweli.lda,voweli)
p.CLvoweli.lda.class = p.CLvoweli.lda$class
p.CLvoweli.lda.table = table(p.CLvoweli.lda.class, voweli$Grouping)
CLvoweli.lda_accur = sum(diag(p.CLvoweli.lda.table))/sum(p.CLvoweli.lda.table)
print(CLvoweli.lda_accur)

CLvowela.lda = lda(Grouping ~ Curvature_Location, data=vowela)
p.CLvowela.lda = predict(CLvowela.lda,vowela)
p.CLvowela.lda.class = p.CLvowela.lda$class
p.CLvowela.lda.table = table(p.CLvowela.lda.class, vowela$Grouping)
CLvowela.lda_accur = sum(diag(p.CLvowela.lda.table))/sum(p.CLvowela.lda.table)
print(CLvowela.lda_accur)


CLvowelu.lda = lda(Grouping ~ Curvature_Location, data=vowelu)
p.CLvowelu.lda = predict(CLvowelu.lda,vowelu)
p.CLvowelu.lda.class = p.CLvowelu.lda$class
p.CLvowelu.lda.table = table(p.CLvowelu.lda.class, vowelu$Grouping)
CLvowelu.lda_accur = sum(diag(p.CLvowelu.lda.table))/sum(p.CLvowelu.lda.table)
print(CLvowelu.lda_accur)


C1vowelu.lda = lda(Grouping ~ real_1, data=vowelu)
p.C1vowelu.lda = predict(C1vowelu.lda,vowelu)
p.C1vowelu.lda.class = p.C1vowelu.lda$class
p.C1vowelu.lda.table = table(p.C1vowelu.lda.class, vowelu$Grouping)
C1vowelu.lda_accur = sum(diag(p.C1vowelu.lda.table))/sum(p.C1vowelu.lda.table)
print(C1vowelu.lda_accur)



C1vowela.lda = lda(Grouping ~ real_1, data=vowela)
p.C1vowela.lda = predict(C1vowela.lda,vowela)
p.C1vowela.lda.class = p.C1vowela.lda$class
p.C1vowela.lda.table = table(p.C1vowela.lda.class, vowela$Grouping)
C1vowela.lda_accur = sum(diag(p.C1vowela.lda.table))/sum(p.C1vowela.lda.table)
print(C1vowela.lda_accur)


C1voweli.lda = lda(Grouping ~ real_1, data=voweli)
p.C1voweli.lda = predict(C1voweli.lda,voweli)
p.C1voweli.lda.class = p.C1voweli.lda$class
p.C1voweli.lda.table = table(p.C1voweli.lda.class, voweli$Grouping)
C1voweli.lda_accur = sum(diag(p.C1voweli.lda.table))/sum(p.C1voweli.lda.table)
print(C1voweli.lda_accur)
```

#LDA Results using acoustics 
```{r}
acoustics7 = lda(Grouping ~ COG + Dispersion + Skewness + F1_mean + F2_mean + F3_mean + F3F2Distance, data=data)

p.acoustics7  = predict(acoustics7,data)
p.acoustics7.class = p.acoustics7$class
p.acoustics7.table = table(p.acoustics7.class,data$Grouping)

acoustics7_accur = sum(diag(p.acoustics7.table))/sum(p.acoustics7.table)

print(acoustics7_accur)


acoustics6 = lda(Grouping ~ COG + Dispersion + Skewness + F1_mean + F2_mean +F3F2Distance, data=data)

p.acoustics6  = predict(acoustics6,data)
p.acoustics6.class = p.acoustics6$class
p.acoustics6.table = table(p.acoustics6.class,data$Grouping)

acoustics6_accur = sum(diag(p.acoustics6.table))/sum(p.acoustics6.table)

print(acoustics6_accur)



acoustics5 = lda(Grouping ~ COG + Dispersion + Skewness + F1_mean + F2_mean, data=data)

p.acoustics5  = predict(acoustics5,data)
p.acoustics5.class = p.acoustics5$class
p.acoustics5.table = table(p.acoustics5.class,data$Grouping)

acoustics5_accur = sum(diag(p.acoustics5.table))/sum(p.acoustics5.table)

print(acoustics5_accur)

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
